export const groupActionTypes = {
    API_RESPONSE_SUCCESS: "@@group/API_RESPONSE_SUCCESS",
    API_RESPONSE_ERROR: "@@group/API_RESPONSE_ERROR",

    GET_ALL_GROUP: "@@group/GET_ALL_GROUP",
    GET_DETAIL_PERMISSION: "@@group/GET_DETAIL_PERMISSION",
}
